# Generated by Django 3.0.2 on 2020-05-10 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_recipes_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materialcontrol',
            old_name='material_id',
            new_name='material',
        ),
        migrations.RenameField(
            model_name='materialcontrol',
            old_name='recipe_id',
            new_name='recipe',
        ),
        migrations.RenameField(
            model_name='recipeprocess',
            old_name='recipe_id',
            new_name='recipe',
        ),
        migrations.RenameField(
            model_name='recipes',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='recipes',
            old_name='recipe_image_id',
            new_name='recipe_image',
        ),
        migrations.RenameField(
            model_name='recipes',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='user_name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.Recipes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Favorites',
                'db_table': 'favorites',
            },
        ),
    ]
