# Generated by Django 3.0.2 on 2020-05-11 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_auto_20200510_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='material',
            field=models.ManyToManyField(through='recipe.MaterialControl', to='recipe.Materials'),
        ),
    ]
